# -*- coding: utf-8 -*-
"""football_players.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFKZfrHwmMWhqhrNIIJYXTUAkIXJbG6F
"""

# -*- coding: utf-8 -*-
"""
Agente 1: Normalizador de Datos
Este agente se encarga de la carga, limpieza, codificación y escalado del dataset players.csv.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

class AgenteNormalizador:
    def __init__(self, input_path, output_path):
        self.input_path = input_path
        self.output_path = output_path
        self.df = None

    def procesar(self):
        # 1. Carga
        self.df = pd.read_csv(self.input_path)

        # 2. Limpieza e Imputación
        numeric_cols = self.df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            if self.df[col].isnull().any():
                self.df[col] = self.df[col].fillna(self.df[col].median())

        # Columnas categóricas
        categorical_cols = ['foot', 'sub_position', 'position', 'domestic_league_code']
        for col in categorical_cols:
            if col in self.df.columns:
                self.df[col] = self.df[col].fillna('Unknown')

        # 3. Codificación (One-Hot Encoding)
        cols_to_encode = [c for c in ['position', 'foot', 'domestic_league_code'] if c in self.df.columns]
        self.df = pd.get_dummies(self.df, columns=cols_to_encode)

        # 4. Escalado (StandardScaler)
        cols_to_scale = [c for c in ['market_value_in_eur', 'height_in_cm', 'age'] if c in self.df.columns]
        scaler = StandardScaler()
        if cols_to_scale:
            self.df[cols_to_scale] = scaler.fit_transform(self.df[cols_to_scale])

        # 5. Exportación
        self.df = self.df.select_dtypes(include=[np.number, 'bool'])
        self.df.to_csv(self.output_path, index=False)

        print('✓ Agente 1: Dataset procesado y players_clean.csv generado correctamente')

# Ejecución del Agente
if __name__ == "__main__":
    normalizador = AgenteNormalizador('players.csv', 'players_clean.csv')
    normalizador.procesar()

    print("\nVista previa del dataset normalizado:")
    print(pd.read_csv('players_clean.csv').head())

    """## Agente 2: Entrenador
Este agente entrena modelos de regresión para predecir el valor de mercado de los jugadores y selecciona el mejor rendimiento.
"""

import pandas as pd
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

class AgenteEntrenador:
    def __init__(self, data_path):
        self.data_path = data_path
        self.df = None
        self.X_train, self.X_test, self.y_train, self.y_test = [None] * 4
        self.results = {}

    def preparar_datos(self):
        self.df = pd.read_csv(self.data_path)
        y = self.df['market_value_in_eur']
        X = self.df.drop(columns=['market_value_in_eur'])
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

    def entrenar_y_evaluar(self):
        modelos = {
            'LinearRegression': LinearRegression(),
            'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42)
        }

        for nombre, modelo in modelos.items():
            # Entrenamiento
            modelo.fit(self.X_train, self.y_train)
            # Predicción
            preds = modelo.predict(self.X_test)
            # Métricas
            r2 = r2_score(self.y_test, preds)
            mae = mean_absolute_error(self.y_test, preds)

            self.results[nombre] = {'R2': r2, 'MAE': mae}

    def seleccionar_y_guardar(self):
        # Determinar el ganador basado en R2
        mejor_modelo = max(self.results, key=lambda x: self.results[x]['R2'])

        metadata = {
            'mejor_modelo': mejor_modelo,
            'metricas_ganador': self.results[mejor_modelo],
            'comparativa_completa': self.results
        }

        with open('resultados_entrenamiento.json', 'w') as f:
            json.dump(metadata, f, indent=4)

        # Mostrar tabla comparativa
        print("--- Comparativa de Modelos ---")
        print(pd.DataFrame(self.results).T)
        print(f"\nModelo Ganador: {mejor_modelo}")
        print('✓ Agente 2: Modelos entrenados y evaluados correctamente')

    def ejecutar_flujo(self):
        self.preparar_datos()
        self.entrenar_y_evaluar()
        self.seleccionar_y_guardar()

# Inicialización y ejecución
entrenador = AgenteEntrenador('players_clean.csv')
entrenador.ejecutar_flujo()
