# -*- coding: utf-8 -*-
"""football_players.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFKZfrHwmMWhqhrNIIJYXTUAkIXJbG6F
"""

# -*- coding: utf-8 -*-
"""
Agente 1: Normalizador de Datos
Este agente se encarga de la carga, limpieza, codificación y escalado del dataset players.csv.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

class AgenteNormalizador:
    def __init__(self, input_path, output_path):
        self.input_path = input_path
        self.output_path = output_path
        self.df = None

    def procesar(self):
        # 1. Carga
        self.df = pd.read_csv(self.input_path)

        # 2. Limpieza e Imputación
        numeric_cols = self.df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            if self.df[col].isnull().any():
                self.df[col] = self.df[col].fillna(self.df[col].median())

        # Columnas categóricas
        categorical_cols = ['foot', 'sub_position', 'position', 'domestic_league_code']
        for col in categorical_cols:
            if col in self.df.columns:
                self.df[col] = self.df[col].fillna('Unknown')

        # 3. Codificación (One-Hot Encoding)
        cols_to_encode = [c for c in ['position', 'foot', 'domestic_league_code'] if c in self.df.columns]
        self.df = pd.get_dummies(self.df, columns=cols_to_encode)

        # 4. Escalado (StandardScaler)
        cols_to_scale = [c for c in ['market_value_in_eur', 'height_in_cm', 'age'] if c in self.df.columns]
        scaler = StandardScaler()
        if cols_to_scale:
            self.df[cols_to_scale] = scaler.fit_transform(self.df[cols_to_scale])

        # 5. Exportación
        self.df = self.df.select_dtypes(include=[np.number, 'bool'])
        self.df.to_csv(self.output_path, index=False)

        print('✓ Agente 1: Dataset procesado y players_clean.csv generado correctamente')

# Ejecución del Agente
if __name__ == "__main__":
    normalizador = AgenteNormalizador('players.csv', 'players_clean.csv')
    normalizador.procesar()

    print("\nVista previa del dataset normalizado:")
    print(pd.read_csv('players_clean.csv').head())